DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
    id SERIAL,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    completed BOOLEAN DEFAULT FALSE,
    imagePath VARCHAR(255) DEFAULT NULL,
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);